CREATE DATABASE IF NOT EXISTS reports;
CREATE DATABASE IF NOT EXISTS blacklists;
CREATE DATABASE IF NOT EXISTS whitelists;
CREATE DATABASE IF NOT EXISTS testaddrlists;
CREATE DATABASE IF NOT EXISTS testtargetlists;
CREATE DATABASE IF NOT EXISTS linktracklists;
CREATE DATABASE IF NOT EXISTS opentracklists;
CREATE DATABASE IF NOT EXISTS assessments;

